### PR TITLE
[CORE-1613] add path validation on cli side: allow only ascii;

### PR DESCRIPTION
**Pull request by opalczynski**

### CODE REVIEW

**Comment by 23doors** [comment]
Shouldn't we validate on backend side though?

**Comment by opalczynski** [comment]
API - returns path invalid - which is good I think.

**Comment by 23doors** [comment]
oh ok, so if it already validates correctly, why do we need it on CLI side as well?

**Comment by opalczynski** [comment]
The error is more specific :) And tells something to user. This is 'pros'. The 'cons' is that why really do not need it.

**Comment by 23doors** [comment]
ok, lgtm then ;)

**Pull request merged**
